spring:
  application:
    name: nacos-discovery-provider

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos

server:
  port: 9091