server:
  port: 9091

spring:
  application:
    name: nacos-discovery-provider

  cloud:
    nacos:
      discovery:
        server-addr: 47.111.114.208:8848
        username: nacos
        password: nacos

  datasource:
    username: consumer
    password: test1234
    url: jdbc:mysql://47.111.114.208:3306/alibaba?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:com.taylor.*.dao.mapper/*Mapper.xml
  type-aliases-package: com.taylor.*.dao.entity