package com.taylor.oauth.dao.mapper;

import com.taylor.oauth.dao.entity.AppEntry;

public interface AppEntryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openapi_auth
     *
     * @mbg.generated Sun Jan 31 16:29:55 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openapi_auth
     *
     * @mbg.generated Sun Jan 31 16:29:55 CST 2021
     */
    int insert(AppEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openapi_auth
     *
     * @mbg.generated Sun Jan 31 16:29:55 CST 2021
     */
    int insertSelective(AppEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openapi_auth
     *
     * @mbg.generated Sun Jan 31 16:29:55 CST 2021
     */
    AppEntry selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openapi_auth
     *
     * @mbg.generated Sun Jan 31 16:29:55 CST 2021
     */
    int updateByPrimaryKeySelective(AppEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openapi_auth
     *
     * @mbg.generated Sun Jan 31 16:29:55 CST 2021
     */
    int updateByPrimaryKey(AppEntry record);
}