server:
  port: 9090

spring:
  application:
    name: nacos-discovery-consumer

  cloud:
    nacos:
      discovery:
        server-addr: 47.111.114.208:8848
        username: nacos
        password: nacos


